# 1 Tensors

In [2]:
import torch
import numpy as np

## 1.1 初始化

### 1. 直接从数据初始化，数据类型可以指定

In [3]:
# torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype=float)    # data 可以是 list，numpy
print(x_data)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


### 2. 根据 Numpy 的数组生成 **torch.from_numpy(ndarray)**

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [24]:
# 利用这个方法创建的 tensor 和原来的 ndarray 共享内存，当修改其中一个数据，另外一个也会被改动。
x_np[1, 1] = 5
print(x_np)
print(np_array)

tensor([[1, 2],
        [3, 5]], dtype=torch.int32)
[[1 2]
 [3 5]]


### 3. 根据另一个 Tensor 的形状和数据类型来生成新的 Tensor，除非通过重写改变了新 Tensor 的形状或数据类型<br>   **torch.ones_like()、torch.rand_like()、torch.zeros_like()**

In [15]:
x_ones = torch.ones_like(x_data)    # 保留原 Tensor 的形状和数据类型！
print(f"Ones Tensor: \n {x_ones} \n")

x_zero = torch.zeros_like(x_np)
print(f"Zeros Tensor: \n {x_zero} \n")

x_rand = torch.rand_like(x_data)
print(f"Random Tensor: \n {x_rand} \n")

x_rand = torch.rand_like(x_np, dtype = float)   # x_np.dtype = int32，这里重写为 float
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]], dtype=torch.int32) 

Random Tensor: 
 tensor([[0.7367, 0.5138],
        [0.9785, 0.7209]], dtype=torch.float64) 

Random Tensor: 
 tensor([[0.1101, 0.1300],
        [0.7923, 0.9408]], dtype=torch.float64) 



### 4. shape 是一个元组，shape 变量决定了 Tensor 的形状/维度，使用 **torch.ones()、torch.rand()、torch.zeros()** 并输入 shape 作为参数来生成 Tensor

In [18]:
shape = (2, 3, 4)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3235, 0.4753, 0.5395],
        [0.1866, 0.7378, 0.0505]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 5.使用某一个值填充某个形状的张量，如 torch.full(size, full_value) 

In [26]:
# torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
tensor = torch.full((3, 2, 2), 6)
print(tensor)

tensor([[[6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6]]])


### 6. 使用 torch.arange()、torch.linspace()、torch.logspace() 创建一维张量

In [27]:
# 创建 [start, end) 的等差一维张量
# torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
tensor = torch.arange(3, 10, 2) # 创建 [3, 10) 内 公差为 2 的等差数列 一维张量
print(tensor)

tensor([3, 5, 7, 9])


In [32]:
# 创建 [start, end] 的均分一维张量
# torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
tensor = torch.linspace(1, 100, 10) # 创建一个 [start, end] 的含有 stpes 个数字的一维均分张量
print(tensor)

tensor([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])


### 7. 使用 torch.eye(n) 创建单位对角矩阵

In [35]:
# torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
tensor = torch.eye(4)
print(tensor)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


## 1.2 根据概率创建 Tensor

## 1.3 Tensor 的属性

In [22]:
tensor = torch.rand(3, 4)                               # 参数中有 *，表示 size 可以输入任意个参数
print(f"Shape of tensor: {tensor.shape}")               # Tensor 的形状
print(f"Datatype of tensor: {tensor.dtype}")            # Tensor 的数据类型
print(f"Device tensor is stored on: {tensor.device}")   # Tensor 的存储设备

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 1. 将张量在原有维度上拼接 torch.cat()

In [38]:
# torch.cat(tensors, dim=0, out=None)
# tensors 表示要拼接的张量序列， dim 表示按照哪个维度进行拼接\

tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)
print(tensor_1)
print(tensor_2)

tensor([[0.6568, 0.3033, 0.0065],
        [0.7642, 0.4486, 0.3084]])
tensor([[0.8015, 0.1249, 0.1277],
        [0.7384, 0.4433, 0.6212]])


In [39]:
tensor_cat = torch.cat([tensor_1, tensor_2], 0)
print(tensor_cat)

tensor([[0.6568, 0.3033, 0.0065],
        [0.7642, 0.4486, 0.3084],
        [0.8015, 0.1249, 0.1277],
        [0.7384, 0.4433, 0.6212]])


In [42]:
tensor_A = torch.rand(2, 1)
tensor_B = torch.rand(2, 5)
tensor_cat = torch.cat([tensor_B, tensor_A], 1)
print(tensor_A)     # tensor_A.size = [2, 1]
print(tensor_B)     # tensor_B.size = [2, 5]
print(tensor_cat)   # tensor_cat.size = [2, 6]

tensor([[0.8660],
        [0.9512]])
tensor([[0.2885, 0.2986, 0.3893, 0.8238, 0.6950],
        [0.1197, 0.7716, 0.1898, 0.7740, 0.8018]])
tensor([[0.2885, 0.2986, 0.3893, 0.8238, 0.6950, 0.8660],
        [0.1197, 0.7716, 0.1898, 0.7740, 0.8018, 0.9512]])


关于在某个维度上的拼接：以二维张量举例，想象两个二维张量 A，B 是两片辣条，其分别在第一维度 x 和第二维度 y 上各有一个竹签。
<br>把 A 和 B 在第一维度上拼接，（如果 Tensors 序列是 [A, B]），也即把辣条 B 沿着辣条 A 的 第一维度 x 的竹签穿进去，A 在上 B 在下。