# Numpy 基础知识

Numpy 提供多维数组对象，其核心是 **ndarry 对象，它封装了相同数据类型的 n 维数组。**
<br>Numpy 数组与标准的 python 数组具有以下区别：
<br>    1. Numpy 数组在创建时**具有固定大小**。更改 ndarry 的大小将创建一个新的数组并删除原值。
<br>    2. Numpy 数组中的元素**具有相同的数据类型**。

**在 Numpy 中，维度叫做轴，轴的个数叫做秩。**
<br>如 [1, 2, 3] 是一个秩为 1 的数组。
<br>如 [[1, 2, 3], 
    [4, 5, 6,]] 是一个秩为 2 的数组。

## Numpy 数组的属性
1. .shape
2. .ndim
3. .dtype.name
4. itemsize
5. size

In [8]:
import numpy as np

a = np.arange(15).reshape(3,5)  # 创建 numpy.ndarray 数组

In [4]:
print(a.shape)  # 输出数组在每个维度上的大小，如一个 m 排 n 列的数组输出 （m, n）

(3, 5)


In [5]:
print(a.ndim)   # 输出数组的维度

2


In [6]:
print(a.dtype.name) # 数组元素的类型

int32


In [7]:
print(a.itemsize)   # 数组元素的字节大小

4


In [9]:
print(a.size)   # 数组元素的个数

15


In [10]:
type(a)

numpy.ndarray

## 创建数组
1. 使用 python 的列表或元组 np.array()。可以指定数据类型。
2. 使用占位符 np.zeros()、np.ones()、np.empty()。可以指定数据类型。
3. np.empty() 随机输出。
4. np.arange([start], stop, [step])
5. np.linspace([start], stop, [num])

1. 使用 python 列表和元组构建数组，所创建的数组由原序列中的元素类型推导而来。

In [14]:
b = np.array([1.5, 37.8, 99.1])
print(b)
print(type(b))

<class 'numpy.ndarray'>


In [17]:
c = np.array([[1, 3, 2], [12, 3.4, 56]], dtype=complex)
print(c)
print(type(c))
print(c.dtype.name)

[[ 1. +0.j  3. +0.j  2. +0.j]
 [12. +0.j  3.4+0.j 56. +0.j]]
<class 'numpy.ndarray'>
complex128


2. 使用占位符创建数组。例如 zeros()、ones()、empty()，默认创建的数组类型是 float64

In [24]:
d = np.zeros((2,3))  # 注意参数只有一个！要括起来！
print(d)
print(d.dtype.name)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [26]:
# 同样可以指定数据类型
print(np.ones((2, 2, 2), dtype=np.int16))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [33]:
print(np.empty((3, 4)))   # 随机输出

[[ 1.   0.   3.   0. ]
 [ 2.   0.  12.   0. ]
 [ 3.4  0.  56.   0. ]]


3. 使用 `np.arange()` 和 `np.linspace()` 函数：

In [34]:
# np.arange([start], stop, [step]) 选择 [start, stop) 的元素，步长为 step，step 可以是浮点数。
e = np.arange(1, 2, 0.2)
print(e)

[1.  1.2 1.4 1.6 1.8]


In [35]:
# 当使用浮点数做参数时，由于浮点数精度有限，通常使用 np.linspace() 函数替代
# np.linspace(start, stop, num)

e = np.linspace(1, 2, 5)
print(e)

[1.   1.25 1.5  1.75 2.  ]


## 基本运算
1. 按照元素位置执行，创建新的数组存储运算结果。例如 + - * **等。
2. 矩阵乘法使用 A.dot(B) 或者 dot(A, B) 实现。
3. 有些操作符像 `+=` 或者 `*=` 被用来更改已存在的数组而不会创建新的数组，因此要注意类型的兼容问题。
4. 当运算数组类型不同时，结果会以更精确的方式存储。（upcast）
6. 统计类运算，例如 .sum()、.max()、.min()等，对数组的形状不敏感，将多维数组视为一维数组。当指定 axis 参数时，可以把运算应用到数组指定的轴上。

Numpy 中数组的算术运算是**按照元素位置执行的**，运算会**创建新的数组并且填充相应位置的结果**。

In [44]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)        # [0 1 2 3]
print(a * b)    # [  0  30  80 150]
print(a - b)    # [20 29 38 47]
print(b ** 2)   # [0 1 4 9]

[0 1 2 3]
[  0  30  80 150]
[20 29 38 47]
[0 1 4 9]


**矩阵乘法可以使用 dot 函数来实现。**

In [46]:
A = np.array([[2, 0], 
              [0, 4]])
B = np.array([[5, 4],
              [3, 4]])
print(A.dot(B))
print(np.dot(A, B))

[[10  8]
 [12 16]]
[[10  8]
 [12 16]]


有些操作符像 `+=` 或者 `*=` 被用来**更改已存在的数组而不会创建新的数组，因此要注意类型的兼容问题**。
<br>**当运算数组类型不同时，结果会以更精确的方式存储。（upcast）**

In [48]:
C = np.ones((2, 3), dtype=int)
D = np.random.random((2, 3))        # dtype = float
print(C)
print(D)

[[1 1 1]
 [1 1 1]]
[[0.04998007 0.04737309 0.93128824]
 [0.4687835  0.53326683 0.29597713]]


In [49]:
D += C
print(D)    # D 的内部数据被改变

[[1.04998007 1.04737309 1.93128824]
 [1.4687835  1.53326683 1.29597713]]


In [50]:
C *= 3
print(C)    # C 的内部数据被改变

[[3 3 3]
 [3 3 3]]


In [51]:
C += D
print(C)    # 由于 C 的 dtype 是 int，D 的 dtype 是 float，不符合 upcast

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [54]:
print(C.dtype.name)
print(D.dtype.name)
E = C + D
print(E.dtype.name) # 以更精确的数据类型存储结果

int32
float64
float64


ndarray 类提供统计类运算，比如对数组所有元素求和，求最大值、最小值。这些运算**默认应用到数组是对数组的形状不敏感的**。当指定 axis 参数时，可以把运算应用到数组指定的轴上。

In [55]:
a = np.random.random((3, 2))
print(a)

[[0.96306832 0.12666451]
 [0.8609113  0.54356207]
 [0.65792257 0.82551705]]


In [57]:
print(a.sum())
print(a.max())
print(a.min())

3.9776458110964916
0.9630683157588489
0.12666451057104278


In [58]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
b.max(axis=0)   # 对于二维数组来说，axis=0 表示按列，

array([ 8,  9, 10, 11])

In [69]:
b.min(axis=1)   # axis=1表示按行

array([0, 4, 8])

In [74]:
c = np.arange(0, 12).reshape(2, 2, 3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [78]:
print(c.max(0))
print(c.min(1))
print(c.sum(2)) # ？？？？？

[[ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [6 7 8]]
[[ 3 12]
 [21 30]]


## 多维数组的索引、切片、迭代（没看完）

In [89]:
b = np.array([[0, 1, 2, 3], 
              [10, 11, 12, 13],
              [20, 21, 22, 23],
              [30, 31, 32, 33],
              [40, 41, 42, 43]])
print(b[2, 3])  # 第 2 行第 3 列的元素，注意行列计数从零开始！
print(b[0:5, 1])    # 第 0 行到第 4 行的第 1 列元素
print(b[:, 1])      # 等价于 b[0:5, 1]
print(b[-1])     # 输出最后一行，等价于 b[-1, :]，等价于 b[1, ...]

23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[40 41 42 43]


In [93]:
# 通过数组索引
a = np.arange(12) ** 2
print(a)
i = np.array([1, 1, 3, 8, 5])
print(a[i])     # 通过数组索引，输出数组中每一个元素在 ndarry 数组对应位置的元素

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  1  9 64 25]


In [96]:
j = np.array([[3, 4], [9, 7]])
print(j)
print(a[j])

[[3 4]
 [9 7]]
[[ 9 16]
 [81 49]]


In [97]:
# 当被索引数组是多维数组时，每一个唯一的索引数列指向此多维数组的第一维
palette = np.array([    [0, 0, 0],
                        [255, 0, 0],
                        [0, 255, 0],
                        [0, 0, 255],
                        [255, 255, 255],
                   ])
image = np.array([
                    [0, 1, 2, 0],
                    [0, 3, 4, 0]
                 ])
print(palette[image])   # image 中的两个四维向量生成了两个含有 4 个元素的数组，其中每个元素是 image 数组中的四维向量中的元素在 palette 数组中对应行的向量，也即，指向第一维

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]


## 改变数组的形状
1. a.ravel() 返回扁平化数组
2. a.shape  返回数组的形状属性
3. a.reshape(x, y) 创建一个新的数组并返回 形状重塑为 x 行 y 列
4. a.T a矩阵的转置
5. a.resize(x, y) 将 a 矩阵形状重塑为 x 行 y 列，并不会创建新数组

In [115]:
a = np.floor(10 * np.random.random((3, 4)))
print(a)
print(a.shape)
b = a.ravel()   # 返回扁平化数组，a 矩阵本身并未改变
print(b)
print(a)

[[5. 1. 1. 5.]
 [3. 5. 5. 5.]
 [7. 2. 3. 5.]]
(3, 4)
[5. 1. 1. 5. 3. 5. 5. 5. 7. 2. 3. 5.]
[[5. 1. 1. 5.]
 [3. 5. 5. 5.]
 [7. 2. 3. 5.]]


In [116]:
c = a.reshape(4, 3) # 返回按四行三列排布的数组，a 矩阵本身并未改变
print(c)
print(a)

[[5. 1. 1.]
 [5. 3. 5.]
 [5. 5. 7.]
 [2. 3. 5.]]
[[5. 1. 1. 5.]
 [3. 5. 5. 5.]
 [7. 2. 3. 5.]]


In [109]:
print(a)
print(a.T)      # a 的转置
print(a.T.shape)

[[3. 9. 9. 2.]
 [5. 1. 1. 8.]
 [6. 8. 0. 7.]]
[[3. 5. 6.]
 [9. 1. 8.]
 [9. 1. 0.]
 [2. 8. 7.]]
(4, 3)


In [117]:
a.resize((2, 6))
print(a)    # a 矩阵本身被改变！

[[5. 1. 1. 5. 3. 5.]
 [5. 5. 7. 2. 3. 5.]]
